### ISSUE TITLE
Problem in Google Function

### ISSUE THREAD

**Issue by marlluslustosa** [btahir/summarlight#1]
Hello. Congratulations on your work.

I'm trying to install your extension as self-hosted and stopped when creating the google function.
Which requirements.txt (main.py refer) did you use?

I had an error regarding the JSON parser:

> textPayload: "Traceback (most recent call last):
>   File "/env/local/lib/python3.7/site-packages/google/cloud/functions/worker.py", line 346, in run_http_function
>     result = _function_handler.invoke_user_function (flask.request)
>   File "/env/local/lib/python3.7/site-packages/google/cloud/functions/worker.py", line 217, in invoke_user_function
>     return call_user_function (request_or_event)
>   File "/env/local/lib/python3.7/site-packages/google/cloud/functions/worker.py", line 210, in call_user_function
>     return self._user_function (request_or_event)
>   File "/user_code/main.py", line 10, in read_article
>     filedata = json.dumps (file_json)
>   File "/opt/python3.7/lib/python3.7/json/__init__.py", line 231, in dumps
>     return _default_encoder.encode (obj)
>   File "/opt/python3.7/lib/python3.7/json/encoder.py", line 199, in encode
>     chunks = self.iterencode (o, _one_shot = True)
>   File "/opt/python3.7/lib/python3.7/json/encoder.py", line 257, in iterencode
>     return _iterencode (o, 0)
>   File "/opt/python3.7/lib/python3.7/json/encoder.py", line 179, in default
>     raise TypeError (f'Object of type {o .__ class __.__ name__} '
> TypeError: Object of type LocalProxy is not JSON serializable

So I researched and saw that I could solve it by changing to jsonify (https://github.com/Miserlou/Zappa/issues/937#issuecomment-309931362).

So I changed main.py with this:

```
from flask import jsonify, escape
...
return jsonify(summary_list)
```

So it works on some sites but on others it gives this error:

> textPayload: "Traceback (most recent call last):
>   File "/env/local/lib/python3.7/site-packages/google/cloud/functions/worker.py", line 346, in run_http_function
>     result = _function_handler.invoke_user_function (flask.request)
>   File "/env/local/lib/python3.7/site-packages/google/cloud/functions/worker.py", line 217, in invoke_user_function
>     return call_user_function (request_or_event)
>   File "/env/local/lib/python3.7/site-packages/google/cloud/functions/worker.py", line 210, in call_user_function
>     return self._user_function (request_or_event)
>   File "/user_code/main.py", line 24, in generate_summary
>     summary_list.remove ('.')
> ValueError: list.remove (x): x not in list
> 

What could be happening?
Big hug and thanks again for sharing your code.

**Comment by btahir** [comment]
Not sure what your output is. Try debugging it by printing out the input and outputs in the generate_summary function. That error is caused on this line: https://github.com/btahir/summarlight/blob/master/main.py#L24
So you can try removing it to see what it gives you.

**Comment by marlluslustosa** [comment]
I left it as it was and apparently it has worked well. In some sites it does not have an expected behavior, generally in very long texts.

Many thanks for the reply.
